spring.application.name=HandyVue

# MyBatis
mybatis.mapper-locations=classpath:mapper/**/*.xml
mybatis.type-aliases-package=org.handy.handyvue.dto

mybatis.configuration.map-underscore-to-camel-case=true
