# 1. Database Connection (Supabase)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://aws-0-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.mqmuouvvrclfiwqmknjy
spring.datasource.password=thsehd6949!